-- CivicMind schema for the Supabase project.
-- Apply this through Supabase SQL Editor or the Supabase CLI.

create extension if not exists pgcrypto;

create table if not exists public.departments (
  id text primary key,
  name text not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.issues (
  id text primary key,
  idempotency_key text not null unique,
  description text not null,
  image_path text not null,
  cctv_frame_path text,
  latitude double precision,
  longitude double precision,
  category text not null default 'other',
  severity text not null default 'medium',
  priority text not null default 'P3',
  priority_score integer not null default 0,
  department text not null default 'Municipal Review',
  status text not null default 'submitted',
  duplicate_count integer not null default 0,
  ai_confidence double precision not null default 0,
  cctv_available boolean not null default false,
  cctv_verified boolean not null default false,
  needs_manual_review boolean not null default false,
  yolo_detections jsonb not null default '[]'::jsonb,
  evidence_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.issue_reports (
  id bigint generated by default as identity primary key,
  issue_id text not null references public.issues(id) on delete cascade,
  reporter_id uuid references auth.users(id) on delete set null,
  image_path text,
  description text,
  latitude double precision,
  longitude double precision,
  image_sha256 text,
  perceptual_hash text,
  created_at timestamptz not null default now()
);

create table if not exists public.status_events (
  id bigint generated by default as identity primary key,
  issue_id text not null references public.issues(id) on delete cascade,
  status text not null,
  actor text not null default 'system',
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists issues_status_idx on public.issues(status);
create index if not exists issues_department_idx on public.issues(department);
create index if not exists issues_category_idx on public.issues(category);
create index if not exists issues_location_idx on public.issues(latitude, longitude);
create index if not exists issue_reports_issue_id_idx on public.issue_reports(issue_id);
create index if not exists status_events_issue_id_idx on public.status_events(issue_id);

insert into public.departments (id, name, description) values
  ('public_works', 'Public Works', 'Roads, potholes, and infrastructure'),
  ('sanitation', 'Sanitation', 'Garbage collection and cleanliness'),
  ('water_drainage', 'Water and Drainage', 'Water supply, leaks, and drainage'),
  ('electrical_services', 'Electrical Services', 'Streetlights and electrical hazards'),
  ('traffic_management', 'Traffic Management', 'Traffic obstruction and mobility'),
  ('municipal_review', 'Municipal Review', 'Unclassified or cross-department issues')
on conflict (id) do update set description = excluded.description;

alter table public.departments enable row level security;
alter table public.issues enable row level security;
alter table public.issue_reports enable row level security;
alter table public.status_events enable row level security;

create policy departments_read on public.departments for select to anon, authenticated using (true);
create policy issues_read on public.issues for select to authenticated using (true);
create policy issues_create on public.issues for insert to authenticated with check (true);
create policy issues_update on public.issues for update to authenticated using (true) with check (true);
create policy issue_reports_read on public.issue_reports for select to authenticated using (true);
create policy issue_reports_create on public.issue_reports for insert to authenticated with check (true);
create policy status_events_read on public.status_events for select to authenticated using (true);
create policy status_events_create on public.status_events for insert to authenticated with check (true);

-- Storage buckets are created separately in the dashboard or with the Storage API.
-- These policies allow authenticated clients to upload/read only CivicMind media.
create policy "authenticated upload issue images" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'issue-images');
create policy "authenticated read issue images" on storage.objects
  for select to authenticated
  using (bucket_id = 'issue-images');
create policy "authenticated upload cctv frames" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'cctv-frames');
create policy "authenticated read cctv frames" on storage.objects
  for select to authenticated
  using (bucket_id = 'cctv-frames');
