import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Bot, CheckCircle2, ChevronLeft, Clock3, MapPin, Navigation, Play, TriangleAlert } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { ErrorPanel, Loading } from "../components/Feedback";
import StatusBadge from "../components/StatusBadge";
import OperationsMap from "../components/map/OperationsMap";
import { useDashboard } from "../hooks/useDashboard";
import { api, errorMessage } from "../lib/api";

export default function DriverPage(){
  const {driverId}=useParams(); const dashboard=useDashboard(); const client=useQueryClient();
  const refresh=()=>client.invalidateQueries({queryKey:["dashboard"]});
  const taskMutation=useMutation({mutationFn:({taskId,status}:{taskId:string;status:"in_progress"|"completed"})=>api.updateTask(taskId,status),onSuccess:refresh});
  const delay=useMutation({mutationFn:()=>api.simulateDelay(driverId!,30),onSuccess:refresh});
  if(dashboard.isLoading)return <Loading label="Loading route…"/>;if(dashboard.isError||!dashboard.data)return <ErrorPanel message={errorMessage(dashboard.error)} retry={()=>dashboard.refetch()}/>;
  const driver=dashboard.data.drivers.find(d=>d.id===driverId);if(!driver)return <ErrorPanel message="This driver does not exist."/>;
  const route=dashboard.data.activePlan?.routes.find(r=>r.driverId===driverId);const orders=new Map(dashboard.data.orders.map(o=>[o.id,o]));const next=route?.stops.find(s=>s.status!=="completed");
  return <div className="mx-auto min-h-screen max-w-3xl p-4 sm:p-6"><Link to="/" className="mb-5 inline-flex items-center gap-1 text-sm text-slate-400 hover:text-white"><ChevronLeft size={17}/>Change driver</Link><header className="panel overflow-hidden"><div className="bg-gradient-to-br from-lime/15 to-cyan/5 p-5 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-lime">Driver route</p><h1 className="mt-2 text-3xl font-black">{driver.name}</h1></div><StatusBadge value={driver.status}/></div><div className="mt-5 flex gap-4 text-sm text-slate-400"><span>{route?.stops.length||0} stops</span><span>{route?.distanceKm.toFixed(1)||"0.0"} km</span><span>{route?.estimatedMinutes||0} min</span></div></div></header><div className="panel mt-4 overflow-hidden p-2"><OperationsMap orders={dashboard.data.orders} drivers={[driver]} plan={dashboard.data.activePlan} selectedDriverId={driver.id} className="h-[320px] sm:h-[420px]"/></div>
    {next?<section className="panel mt-4 border-lime/30 p-5 sm:p-6"><p className="text-xs font-bold uppercase tracking-[.18em] text-lime">Next stop</p><h2 className="mt-3 text-2xl font-black">{orders.get(next.orderId)?.address||next.orderId}</h2><p className="mt-2 text-sm text-slate-400">{orders.get(next.orderId)?.customerName} · demand {orders.get(next.orderId)?.demand}</p><div className="mt-5 flex items-center gap-2 text-sm"><Clock3 size={17} className="text-cyan"/>ETA {new Date(next.eta).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</div><div className="mt-4 rounded-xl border border-cyan/20 bg-cyan/5 p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-cyan"><Bot size={16}/>AI delivery instruction</div><p className="mt-2 text-sm leading-6 text-slate-200">{next.instruction}</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{next.taskId&&<><button className="button-secondary" disabled={taskMutation.isPending} onClick={()=>taskMutation.mutate({taskId:next.taskId!,status:"in_progress"})}><Play size={16}/>Start task</button><button className="button-primary" disabled={taskMutation.isPending} onClick={()=>taskMutation.mutate({taskId:next.taskId!,status:"completed"})}><CheckCircle2 size={16}/>Complete task</button></>}<a className="button-secondary sm:col-span-2" href={`https://www.openstreetmap.org/directions?to=${orders.get(next.orderId)?.latitude},${orders.get(next.orderId)?.longitude}`} target="_blank" rel="noreferrer"><Navigation size={16}/>Open turn-by-turn route</a></div></section>:<section className="panel mt-4 p-8 text-center"><CheckCircle2 className="mx-auto text-lime" size={34}/><h2 className="mt-3 font-bold">Route complete</h2><p className="mt-1 text-sm text-slate-500">No unfinished stops are assigned.</p></section>}
    {(taskMutation.error||delay.error)&&<p className="mt-4 rounded-xl border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-200">{errorMessage(taskMutation.error||delay.error)}</p>}
    <section className="panel mt-4 p-5"><div className="flex items-center justify-between"><h2 className="font-bold">Route sequence</h2><button className="inline-flex items-center gap-1.5 text-xs font-bold text-amber-300" disabled={delay.isPending} onClick={()=>delay.mutate()}><TriangleAlert size={15}/>{delay.isPending?"Reporting…":"Report 30 min delay"}</button></div><div className="mt-5 space-y-1">{route?.stops.map(stop=>{const order=orders.get(stop.orderId);return <div key={stop.orderId} className="grid grid-cols-[32px_1fr_auto] items-center gap-3 rounded-xl p-3 hover:bg-white/[.03]"><div className="grid h-8 w-8 place-items-center rounded-full border border-line text-xs font-bold">{stop.sequence}</div><div><div className="flex items-center gap-1.5 text-sm font-bold"><MapPin size={13} className="text-cyan"/>{order?.address||stop.orderId}</div><div className="mt-1 text-xs text-slate-500">ETA {new Date(stop.eta).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</div></div><StatusBadge value={stop.status}/></div>})}{!route?.stops.length&&<p className="py-6 text-center text-sm text-slate-500">Generate a plan to receive tasks.</p>}</div></section>
  </div>
}
